### ISSUE TITLE
Wrong status code

### ISSUE THREAD

**Issue by ghost** [danielace1/sportify-nexus#7]
```const getPlayerDatas = async (req, res) => {
  try {
    const playerDetails = await playerData.find({});
    res.status(200).json(playerDetails);
  } catch (error) {
    res.json({ status: 200, message: error.message });
  }
};
```
In http requests, status 200 means ok. but code supposed to `catch` the error or either way you can add the catch's error message or make yourself a meaningful error handler. :) 
```
const getPlayerData = async (req,res) => {
  try {
    const playerDetails = await playerData.find({});
    res.json(playerDetails);
  } catch(error) {
    res.status(500).json({message: error.message || "Server Error"})
  }
}
```

**Comment by sharif-22** [comment]
Thanks! @mshajid for noticing mistake and we thought that to show the error msg in UI and mentioning that req as success and the error msg.

after the issue i rewrite that part with proper validation and added new endpoint to add new sport to profile 
please check that lines and let me know the errors and best practices

**Comment by mshajid** [comment]
yeah sure about that @sharif-22 . once you complete it let me know.

**Comment by ghost** [comment]
> Thanks! @mshajid for noticing mistake and we thought that to show the error msg in UI and mentioning that req as success and the error msg.
> 
> after the issue i rewrite that part with proper validation and added new endpoint to add new sport to profile 
> please check that lines and let me know the errors and best practices 

sure thing sharif. ill raise an issue ticket.
